[package]
name = "kak-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.30.1", features = ["fs"] }
tokio = { version = "1.49.0", features = ["rt", "macros", "fs", "io-util", "process", "sync", "rt-multi-thread"] }
